apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2019-03-22T22:48:32Z","generation":3,"labels":{"app":"localization-api"},"name":"localization-api","namespace":"default","resourceVersion":"20534","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/localization-api","uid":"9e45a666-4cf4-11e9-ad11-42010a9c024c"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"localization-api"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"localization-api"}},"spec":{"containers":[{"image":"docker.io/maruf571/localization-api:1.0.1-SNAPSHOT","imagePullPolicy":"Always","name":"localization-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2019-03-22T22:52:07Z","lastUpdateTime":"2019-03-22T22:52:07Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: 2019-03-23T18:33:27Z
  generation: 1
  labels:
    app: localization-api
  name: localization-api
  namespace: default
  resourceVersion: "11817"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/localization-api
  uid: 267a99e5-4d9a-11e9-a5e7-42010a9c002a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: localization-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: localization-api
    spec:
      containers:
        - image: docker.io/maruf571/localization-api:1.0.2-SNAPSHOT
          imagePullPolicy: Always
          name: localization-api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2019-03-23T18:33:27Z
      lastUpdateTime: 2019-03-23T18:33:27Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
